- hosts: local
  connection: local
  become: true
  tasks: 
    - name: Copy files to host
      git:
        repo: https://github.com/patrick-biegon/travel-app.git
        dest: /var/www/html
        force: yes 